# Configuration du Portfolio
title: "PARENT Alban"
description: "Portfolio d'un étudiant en Réseaux & Télécommunications"

# Options du thème console
style: dark
listen_for_clients_preferred_style: true

# Plugins obligatoires pour le thème
plugins:
  - jekyll-seo-tag
